### ISSUE TITLE
Heroku build & deploy

### ISSUE THREAD

**Issue by JanMikes** [deprecated-packages/open-training#5]
Solves problem with running and auto deploying/building app on heroku.

**Comment by TomasVotruba** [comment]
You can put this right into PR, keep it simple :+1:

**Comment by JanMikes** [comment]
@TomasVotruba sorry, i disconnected autodeploy by accident, i wanted to change it to `heroku` branch instead of `master`, could you fix that up please? :-)

**Comment by TomasVotruba** [comment]
Sure I can :+1:

**Comment by JanMikes** [comment]
After this is closed, do not forget to change it back to master, i will add it to PR to checklist.

**Comment by TomasVotruba** [comment]
I can't find it after 3 minutes :/

https://dashboard.heroku.com/apps/pehapkari-open-lecture/settings

You have access, feel free to change it

**Comment by JanMikes** [comment]
It is in tab `Deploy`, i can not, because repository is under `TomasVotruba` "organization" and it does not appear in my selectbox :-) 

<img width="1287" alt="screenshot 2018-08-17 00 03 20" src="https://user-images.githubusercontent.com/3995003/44237522-0fbb0c00-a1b1-11e8-9c88-c9223ed23e8b.png">

**Comment by TomasVotruba** [comment]
Oh, I see. It's on :+1:
